webtalk_init -webtalk_dir C:/Users/hadys/Desktop/verilog/chatgpt/UART_TX_project/UART_TX_project.sim/sim_1/behav/xsim/xsim.dir/TX_module_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug  7 14:54:10 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c8a22dc6-c043-45a2-83f2-9a3d598a8e40" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a6e58e2fde6148ee874dd93751a0a394" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "400" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7660650 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.34_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16884_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2461723458 -regid "" -xml C:/Users/hadys/Desktop/verilog/chatgpt/UART_TX_project/UART_TX_project.sim/sim_1/behav/xsim/xsim.dir/TX_module_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hadys/Desktop/verilog/chatgpt/UART_TX_project/UART_TX_project.sim/sim_1/behav/xsim/xsim.dir/TX_module_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hadys/Desktop/verilog/chatgpt/UART_TX_project/UART_TX_project.sim/sim_1/behav/xsim/xsim.dir/TX_module_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
